version: '3.8'

services:
  pan_saver:
    build: .
    container_name: pan_saver
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./tmp:/tmp/pan_saver
      - ./log:/var/log
      # - ./app:/app
      - ./tg_data:/var/lib/telegram-bot-api
    extra_hosts:
      - "pcs.baidu.com:36.110.192.115"
      - "pcs.baidu.com:111.63.96.140"

  telegram-bot-api:
    image: aiogram/telegram-bot-api:latest
    container_name: telegram-bot-api
    restart: unless-stopped
    environment:
      TELEGRAM_API_ID: "${TG_API_ID:-}"
      TELEGRAM_API_HASH: "${TG_API_HASH:-}"
      TELEGRAM_STAT: 1
      TELEGRAM_LOCAL: 1
    volumes:
      - ./tg_data:/var/lib/telegram-bot-api
    ports:
      - "127.0.0.1:8081:8081"
